-- PUBLIC.BK_BOOKS definition

-- Drop table

-- DROP TABLE BK_BOOKS;

CREATE TABLE BK_BOOKS
(
    BOOK_ID      INTEGER  NOT NULL AUTO_INCREMENT,
    TITLE        VARCHAR(100),
    AUTHOR       VARCHAR(100),
    PUBLISHER    VARCHAR(100),
    PUBLISH_DATE DATE,
    PRICE        DECIMAL(10, 2),
    CATEGORY     VARCHAR(100),
    SUMMARY      VARCHAR(500),
    KEYWORDS     VARCHAR(100),
    DEL_FLAG     TINYINT NOT NULL  DEFAULT 0                                                                                NOT NULL,
    CREATE_TIME  TIMESTAMP,
    CREATE_NAME  VARCHAR(100),
    UPDATE_NAME  VARCHAR(100),
    UPDATE_TIME  TIMESTAMP,
    CONSTRAINT BK_BOOKS_PK PRIMARY KEY (BOOK_ID)
);


-- PUBLIC.M_SYS_MENU definition

-- Drop table

-- DROP TABLE M_SYS_MENU;

CREATE TABLE M_SYS_MENU
(
    ID            INTEGER NOT NULL AUTO_INCREMENT,
    VIEW_URL      VARCHAR(255),
    MAPPER_URL    VARCHAR(500),
    MODULE_NAME   VARCHAR(255),
    "type"        TINYINT,
    ICON          VARCHAR(255),
    PARENT_ID     INTEGER NOT NULL DEFAULT 0 ,
    DEL_STATUS    TINYINT NOT NULL DEFAULT 0 ,
    ENABLE_STATUS TINYINT NOT NULL DEFAULT 1  ,
    CREATE_TIME   TIMESTAMP,
    UPDATE_TIME   TIMESTAMP,
    OPERATOR      VARCHAR(100) NOT NULL DEFAULT 'system' ,
    LABEL_UNQ     VARCHAR(100),
    SORT          INTEGER NOT NULL DEFAULT 0 ,
    IS_FIXED      TINYINT NOT NULL DEFAULT 0 ,
    CONSTRAINT NEWTABLE_PK PRIMARY KEY (ID)
);

-- PUBLIC.JK_BACKEND_ADMIN definition

-- Drop table

-- DROP TABLE JK_BACKEND_ADMIN;

CREATE TABLE JK_BACKEND_ADMIN
(
    USERNAME        VARCHAR(100),
    PASSWORD        VARCHAR(100),
    EMAIL           VARCHAR(45),
    MOBILE          VARCHAR(100),
    STATUS          TINYINT,
    CREATED_AT      TIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    LAST_LOGIN_IP   VARCHAR(100),
    LAST_LOGIN_TIME TIMESTAMP,
    IS_FIXED        TINYINT,
    ID              INTEGER  NOT NULL AUTO_INCREMENT,
    CONSTRAINT JK_BACKEND_ADMIN_PK PRIMARY KEY (ID)
);


-- PUBLIC.JK_AUTH_GROUP_ACCESS definition

-- Drop table

-- DROP TABLE JK_AUTH_GROUP_ACCESS;

CREATE TABLE JK_AUTH_GROUP_ACCESS
(
    UID      INTEGER NOT NULL,
    GROUP_ID INTEGER NOT NULL,
    CONSTRAINT JK_AUTH_GROUP_ACCESS_PK PRIMARY KEY (UID, GROUP_ID)
);


-- PUBLIC.JK_AUTH_GROUP definition

-- Drop table

-- DROP TABLE JK_AUTH_GROUP;

CREATE TABLE JK_AUTH_GROUP
(
    ID          INTEGER  NOT NULL AUTO_INCREMENT,
    TITLE       VARCHAR(100),
    DESCRIPTION VARCHAR(100),
    STATUS      TINYINT,
    RULES       VARCHAR(1000),
    CONSTRAINT JK_AUTH_GROUP_PK PRIMARY KEY (ID)
);