server:
  port: 8089
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    sql-script-encoding: UTF-8
    schema: classpath:/db/1.sql
    data: classpath:/db/2.sql
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&
    #    username: root
    #    password: 123456
    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:file:./db/testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=true;
    url: jdbc:h2:mem:proddb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=true;
    username: root
    password: root
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML
    cache: false

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/ , file:static/upload
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 150MB
#日志打印级别
logging:
  level:
    root: info
    com.marubi.security.system.mapper: debug
    com.marubi.security.business.mapper: debug

#solt
admin:
  solt: amazing
marubi:
  jwt:
    key: nice
  pre:
    address: http://127.0.0.1:${server.port}
